baseURL = "https://supersecurepayment.com/"
languageCode = "en-us"
title = "Super Secure Payment Online"
theme ="hugo-universal-theme"
style = "blue"

[params]
	email = "example@example.com"
	latitude = "-12.043333"
    	longitude = "-77.028333"
    	direction = "Desamparados Station, Distrito de Lima 15001, Peru"

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    name = "Transaction"
    url  = "/transaction/"
    weight = 3

[[menu.main]]
	name = "Contact"
	url = "/contacts"
	weight = 4

[params.carousel]
    enable = true

[params.testimonials]
    enable = true
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."